alter table TRAININGTASK_COMPANY add constraint FK_TRAININGTASK_COMPANY_ID foreign key (ID) references TRAININGTASK_CUSTOMER(ID);
create unique index IDX_TRAININGTASK_COMPANY_UNIQ_INN on TRAININGTASK_COMPANY (INN) ;
