create unique index IDX_TRAININGTASK_CUSTOMER_UNIQ_EMAIL on TRAININGTASK_CUSTOMER (EMAIL) ;
create unique index IDX_TRAININGTASK_CUSTOMER_UNIQ_INN on TRAININGTASK_CUSTOMER (INN) ;
create unique index IDX_TRAININGTASK_CUSTOMER_UNIQ_PASSPORT_NO on TRAININGTASK_CUSTOMER (PASSPORT_NO) ;
