alter table TRAININGTASK_INDIVIDUAL add constraint FK_TRAININGTASK_INDIVIDUAL_ID foreign key (ID) references TRAININGTASK_CUSTOMER(ID);
create unique index IDX_TRAININGTASK_INDIVIDUAL_UNIQ_PASSPORT_NO on TRAININGTASK_INDIVIDUAL (PASSPORT_NO) ;
