-- begin TRAININGTASK_EMPLOYEE
alter table TRAININGTASK_EMPLOYEE add constraint FK_TRAININGTASK_EMPLOYEE_CENTER foreign key (CENTER_ID) references TRAININGTASK_CAR_SERVICE_CENTER(ID)^
create unique index IDX_TRAININGTASK_EMPLOYEE_UNIQ_EMAIL on TRAININGTASK_EMPLOYEE (EMAIL) ^
create index IDX_TRAININGTASK_EMPLOYEE_CENTER on TRAININGTASK_EMPLOYEE (CENTER_ID)^
-- end TRAININGTASK_EMPLOYEE
-- begin TRAININGTASK_CUSTOMER
create unique index IDX_TRAININGTASK_CUSTOMER_UNIQ_EMAIL on TRAININGTASK_CUSTOMER (EMAIL) ^
-- end TRAININGTASK_CUSTOMER
-- begin TRAININGTASK_REPAIR
alter table TRAININGTASK_REPAIR add constraint FK_TRAININGTASK_REPAIR_EMPLOYEE foreign key (EMPLOYEE_ID) references TRAININGTASK_EMPLOYEE(ID)^
alter table TRAININGTASK_REPAIR add constraint FK_TRAININGTASK_REPAIR_CENTER foreign key (CENTER_ID) references TRAININGTASK_CAR_SERVICE_CENTER(ID)^
create index IDX_TRAININGTASK_REPAIR_EMPLOYEE on TRAININGTASK_REPAIR (EMPLOYEE_ID)^
create index IDX_TRAININGTASK_REPAIR_CENTER on TRAININGTASK_REPAIR (CENTER_ID)^
-- end TRAININGTASK_REPAIR
-- begin TRAININGTASK_CAR_SERVICE_CENTER
alter table TRAININGTASK_CAR_SERVICE_CENTER add constraint FK_TRAININGTASK_CAR_SERVICE_CENTER_CITY foreign key (CITY_ID) references TRAININGTASK_CITY(ID)^
create index IDX_TRAININGTASK_CAR_SERVICE_CENTER_CITY on TRAININGTASK_CAR_SERVICE_CENTER (CITY_ID)^
-- end TRAININGTASK_CAR_SERVICE_CENTER
-- begin TRAININGTASK_CUSTOMER_CAR_SERVICE_CENTER_LINK
alter table TRAININGTASK_CUSTOMER_CAR_SERVICE_CENTER_LINK add constraint FK_TCCSCL_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references TRAININGTASK_CAR_SERVICE_CENTER(ID)^
alter table TRAININGTASK_CUSTOMER_CAR_SERVICE_CENTER_LINK add constraint FK_TCCSCL_CUSTOMER foreign key (CUSTOMER_ID) references TRAININGTASK_CUSTOMER(ID)^
-- end TRAININGTASK_CUSTOMER_CAR_SERVICE_CENTER_LINK
-- begin TRAININGTASK_INDIVIDUAL
alter table TRAININGTASK_INDIVIDUAL add constraint FK_TRAININGTASK_INDIVIDUAL_ID foreign key (ID) references TRAININGTASK_CUSTOMER(ID)^
create unique index IDX_TRAININGTASK_INDIVIDUAL_UNIQ_PASSPORT_NO on TRAININGTASK_INDIVIDUAL (PASSPORT_NO) ^
-- end TRAININGTASK_INDIVIDUAL
-- begin TRAININGTASK_COMPANY
alter table TRAININGTASK_COMPANY add constraint FK_TRAININGTASK_COMPANY_ID foreign key (ID) references TRAININGTASK_CUSTOMER(ID)^
create unique index IDX_TRAININGTASK_COMPANY_UNIQ_INN on TRAININGTASK_COMPANY (INN) ^
-- end TRAININGTASK_COMPANY
