-- begin TRAININGTASK_EMPLOYEE
alter table TRAININGTASK_EMPLOYEE add constraint FK_TRAININGTASK_EMPLOYEE_CENTER1 foreign key (CENTER_ID) references TRAININGTASK_CAR_SERVICE_CENTER(ID)^
create unique index IDX_TRAININGTASK_EMPLOYEE_UK_EMAIL1 on TRAININGTASK_EMPLOYEE (EMAIL) where DELETE_TS is null ^
create index IDX_TRAININGTASK_EMPLOYEE_CENTER on TRAININGTASK_EMPLOYEE (CENTER_ID)^
-- end TRAININGTASK_EMPLOYEE
-- begin TRAININGTASK_CUSTOMER
create unique index IDX_TRAININGTASK_CUSTOMER_UK_EMAIL1 on TRAININGTASK_CUSTOMER (EMAIL) where DELETE_TS is null ^
-- end TRAININGTASK_CUSTOMER
-- begin TRAININGTASK_REPAIR
alter table TRAININGTASK_REPAIR add constraint FK_TRAININGTASK_REPAIR_EMPLOYEE foreign key (EMPLOYEE_ID) references TRAININGTASK_EMPLOYEE(ID)^
alter table TRAININGTASK_REPAIR add constraint FK_TRAININGTASK_REPAIR_CENTER foreign key (CENTER_ID) references TRAININGTASK_CAR_SERVICE_CENTER(ID)^
create index IDX_TRAININGTASK_REPAIR_EMPLOYEE on TRAININGTASK_REPAIR (EMPLOYEE_ID)^
create index IDX_TRAININGTASK_REPAIR_CENTER on TRAININGTASK_REPAIR (CENTER_ID)^
-- end TRAININGTASK_REPAIR
-- begin TRAININGTASK_INDIVIDUAL
alter table TRAININGTASK_INDIVIDUAL add constraint FK_TRAININGTASK_INDIVIDUAL_ID foreign key (ID) references TRAININGTASK_CUSTOMER(ID)^
-- end TRAININGTASK_INDIVIDUAL
-- begin TRAININGTASK_COMPANY
alter table TRAININGTASK_COMPANY add constraint FK_TRAININGTASK_COMPANY_ID foreign key (ID) references TRAININGTASK_CUSTOMER(ID)^
-- end TRAININGTASK_COMPANY
-- begin TRAININGTASK_CAR_SERVICE_CENTER
alter table TRAININGTASK_CAR_SERVICE_CENTER add constraint FK_TRAININGTASK_CAR_SERVICE_CENTER_CITY1 foreign key (CITY_ID) references TRAININGTASK_CITY(ID)^
alter table TRAININGTASK_CAR_SERVICE_CENTER add constraint FK_TRAININGTASK_CAR_SERVICE_CENTER_CREATED_BY_USER1 foreign key (CREATED_BY_USER_ID) references SEC_USER(ID)^
create index IDX_TRAININGTASK_CAR_SERVICE_CENTER_CITY on TRAININGTASK_CAR_SERVICE_CENTER (CITY_ID)^
create index IDX_TRAININGTASK_CAR_SERVICE_CENTER_CREATED_BY_USER on TRAININGTASK_CAR_SERVICE_CENTER (CREATED_BY_USER_ID)^
-- end TRAININGTASK_CAR_SERVICE_CENTER
-- begin TRAININGTASK_CAR_SERVICE_CENTER_CUSTOMER_LINK
alter table TRAININGTASK_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_TCSCCL_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references TRAININGTASK_CAR_SERVICE_CENTER(ID)^
alter table TRAININGTASK_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_TCSCCL_CUSTOMER foreign key (CUSTOMER_ID) references TRAININGTASK_CUSTOMER(ID)^
-- end TRAININGTASK_CAR_SERVICE_CENTER_CUSTOMER_LINK
-- begin TRAININGTASK_CITY
create unique index IDX_TRAININGTASK_CITY_UK_NAME1 on TRAININGTASK_CITY (NAME) where DELETE_TS is null ^
-- end TRAININGTASK_CITY
